added Smart Pointers Code
DevAffan/AffiCodes-Hacktoberfest2024 pull request #151
Opened 2024-10-01 12:11 UTC by Virus2466

Added Smart Pointers Introduction with Helpful Comments!.

2024-10-01 13:12 UTC, DevAffan requested changes
Hi, can you please add .vscode folder/files to .gitignore to make file structure more clear.

2024-10-01 17:28 UTC, Virus2466 commented
yeah sure no problem.

2024-10-02 05:19 UTC, DevAffan requested changes
hi, it still showing .vscode folder here.
please add .gitignore file and add .vscode folder name there to avoid push.

Thank you

2024-10-02 06:03 UTC, DevAffan approved these changes

2024-10-02 06:03 UTC, merged